before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"