name: Run Integration Tests

on:
  push

jobs:
  tests:
    #strategy:
    #  matrix:
    #    os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ubuntu-latest
    name: Ubuntu Integration Tests
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: "${GITHUB_WORKSPACE}/cmd/integration_tests.sh"

