name: Run Integration Tests

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - master
      - main

jobs:
  tests:
    # TODO: Run integration tests on Windows and maybe Mac
    #strategy:
    #  matrix:
    #    os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ubuntu-latest
    name: Ubuntu Integration Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: "chmod +x ${GITHUB_WORKSPACE}/cmd/integration_tests.sh && ${GITHUB_WORKSPACE}/cmd/integration_tests.sh"

